version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    volumes:
      - backend_data:/app/backend
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    networks:
      - cognitive-triage-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    networks:
      - cognitive-triage-network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:

networks:
  cognitive-triage-network:
    driver: bridge 