version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend_data:/app/backend
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - cognitive-triage-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    networks:
      - cognitive-triage-network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:

networks:
  cognitive-triage-network:
    driver: bridge 