version: '3.8'

services:
  cognitive-triage:
    build:
      context: .
      dockerfile: Dockerfile.single
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - backend_data:/app/backend
    restart: unless-stopped

volumes:
  backend_data: